### ISSUE TITLE
Povezava za Binder

### ISSUE THREAD

**Issue by katarinabrilej** [BulaRebula/APPR-2019-20#1]
Vidim, da še nisi popravil povezave za Binder. To narediš tako, da v README.md popraviš naslednji vrstici, kjer uporabnisko ime jaanos zamenjaš s svojim uporabniškim imenom.
```
* [![Shiny](http://mybinder.org/badge.svg)](http://mybinder.org/v2/gh/jaanos/APPR-2019-20/master?urlpath=shiny/APPR-2019-20/projekt.Rmd) Shiny
* [![RStudio](http://mybinder.org/badge.svg)](http://mybinder.org/v2/gh/jaanos/APPR-2019-20/master?urlpath=rstudio) RStudio
```
Svetujem ti tudi, da datoteko za uvoz podatkov `UVOZ_CSV.R` preimenuješ v `UVOZ_CSV.r` (torej končnica .r namesto .R), saj se preostale datoteke končajo z .r (v primeru da bi potem to datoteko poklical z `UVOZ_CSV.R`  bi to na Windowsih in Macu delovalo, na Linuxu pa ne).

Prav tako v datoteki za uvoz ne rabiš posebej klicati knjižnic, ampak sledeča ukaza dodaš v datoteko libraries.r v mapi lib in potem to poženeš vsakič pred začetkom dela.
```
library(readr)
library(dplyr)
```

**Comment by BulaRebula** [comment]
Hvala za opozorilo.
Popravil sem vse, le pri preimenovanju datoteke iz .R v .r imam tezave.

**Comment by jaanos** [comment]
Verjetno bo najlažje, da preimenovanje izvedeš kar na GitHubu (uredi datoteko, pa lahko tam spremeniš tudi ime). Sicer pa ni narobe, če je končnica `.R`, samo kot tako jo navajaj v kodi.
