### ISSUE TITLE
Filtriranje Tabele glede na spisek drzav

### ISSUE THREAD

**Issue by BulaRebula** [BulaRebula/APPR-2019-20#3]
Že večkrat sem se srečal s težavo, ki sem se ji do sedaj izogibal.
Imam tabele z državami, ki imajo ali eno vrednost ali pa nekaj (za vsako leto eno).
Rad bi ustvaril nek enoten seznam držav za katere imam vse podatke, (ena tabela vsebuje zadovoljstvo, ena BDP ena pa nezaposlenost).  Uspešno ustvarim tabelo velikosti n x 1, a se po mojem mnenju zaplete, ko probam to spremeniti v string in nato filtrirati.
primer za eno tabelo:
(spisek_drzav_1 je tabela drzav iz prejsnje tabele)
```R
uvozi.BDP <- function(rating) {
  BDP_na_prebivalca <- read_csv("podatki/Main_GDP_aggregates_per_capita.csv", 
    col_names=c("Drzava",2013:2018),
    skip=17,n_max=37, na=":",locale=locale(encoding="CP1250")) %>% drop_na()
  spisek_drzav_2 <- BDP_na_prebivalca %>% select(Drzava)
  spisek_drzav <- inner_join(spisek_drzav_1,spisek_drzav_2, by = c("Drzava"))
  BDP <- BDP_na_prebivalca %>% filter(Drzava %in% c(spisek_drzav))
}
```

**Comment by jaanos** [comment]
Razpredelnici `spisek_drzav_1` in `spisek_drzav_2` definiraš vsako v svoji funkciji, tako da izven funkcij nista vidni. Svetujem še, da parameter `rating` odstraniš, saj ga ne potrebuješ (funkcijo tudi kličeš brez parametra).

Če vendarle dobiš razpredelnico `spisek_drzav` s stolpcem `Drzava`, lahko vsebovanost potem preverjaš z `Drzava %in% spisek_drzav$Drzava`. Sicer pa načeloma ni problema, če za nekatere države ni vseh podatkov. Če se za posamezno analizo izkaže, da je to problem, filtriranje narediš takrat.

Mimogrede, opažam, da v `libraries.r` kličeš funkcijo `install.packages` - tega ne počni, pač pa knjižnice enostavno uvozi z ukazom `library` (če je uporabnik nima, bo moral sam poskrbeti za njeno namestitev).
