### ISSUE TITLE
Sprememba paketa data.world

### ISSUE THREAD

**Issue by BulaRebula** [BulaRebula/APPR-2019-20#5]
Kar nekajkrat sem uporabil paket `data.world` v svoji kodi a sedaj, ko sem hotel počasi zaključiti svoj projekt imam težave s tem paketom. Kot razumem so ga izbrisali (ne vem a ravno sedaj ali sem ga prej nekako ponesreči uspel namestiti).
![image](https://user-images.githubusercontent.com/40576807/75624597-199b3900-5bb6-11ea-8ec6-3b23e9f6cf65.png)

Ali lahko še vedno nekako prelisicim R ali obstaja kakšen podoben paket (zaenkrat ga še nisem našel).
V arhivu [CRAN-a](https://cran.r-project.org/src/contrib/Archive/data.world/) sem našel paket, a ga kljub nekaj poskusom nisem uspešno namestil.

LP,
Aljoša

**Comment by BulaRebula** [comment]
Med poskusi nameščanja mi izpisuje tudi tak error:
![image](https://user-images.githubusercontent.com/40576807/75625052-9203f900-5bba-11ea-8d5e-460b4fec4025.png)

**Comment by jaanos** [comment]
Na repozitoriju paketa svetujejo, naj se ga namesti neposredno iz GitHuba:

https://github.com/datadotworld/data.world-r#installation

Sicer pa upam, da tega paketa ne boš potreboval (kolikor vidim, je potrebno pridobiti API žeton, ki ne sme biti javno objavljen) ter da lahko njegovo funkcionalnost nadomestiš z drugimi uvoženimi knjižnicami (sem jih sedaj dodal v sliko za Docker, tako da boš lahko poganjal, ko boš imel pripravljeno poročilo).

**Comment by jaanos** [comment]
Če boš za pridobitev svojih podatkov potreboval API žeton, glej https://github.com/Babnik21/APPR-2019-20/issues/3#issuecomment-596463678.
